name: Proxy updater

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * *

jobs:
  parser:
    runs-on: ubuntu-latest
    name: Proxy updater
    steps:
      - name: Install Node.js
        run: sudo apt-get update && sudo apt-get install nodejs chromium-browser -y

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        working-directory: ./.github/actions/parxyParser/
        run: node node_modules/.bin/cypress install

      - name: Parse proxies to file
        working-directory: ./.github/actions/parxyParser/
        env:
          KEY: ${{ secrets.proxy_key }}
        run: node node_modules/.bin/cypress run --spec "cypress/integration/index.js" --headless --env proxy_key=$KEY -b chromium

      - name: Move http to proxy folder
        run: mv ./.github/actions/parxyParser/prox.txt ./files/paid/http.txt

      - name: Move socks4 to proxy folder
        run: mv ./.github/actions/parxyParser/socks4.txt ./files/paid/sock4.txt

      - name: Move socks5 to proxy folder
        run: mv ./.github/actions/parxyParser/socks5.txt ./files/paid/sock5.txt

      - name: Add http proxydb proxies
        run: cat ./files/proxydb/http.txt >> ./files/paid/http.txt

      - name: Add socks4 proxydb proxies
        run: cat ./files/proxydb/sock4.txt >> ./files/paid/sock4.txt

      - name: Add socks5 proxydb proxies
        run: cat ./files/proxydb/sock5.txt >> ./files/paid/sock5.txt

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Proxy update
          commit_options: '--no-verify --signoff'
          file_pattern: ./files/paid/*.txt
